version: '3'
services:
  # The Application
  app:
    build: .
    volumes:
      - .:/usr/src/app 
    image:    javedsaqib/sit323-737-2023-t1-prac5p_app
    container_name: firstimagecompose
    restart: always
    ports:
        - 8071:8080
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    
  second:
    build: .
    volumes:
      - .:/usr/src/second
    image:    javedsaqib/network-test-1
    container_name: secondconatinertestcompose
    restart: always
    ports:
        - 8075:8080
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    